name: Main
on:
  push:

jobs: 

  # Builds the image and publishes it on docker hub - only for pushes in main
  build_and_push_docker:
    runs-on: ubuntu-latest
    if: "${{ github.ref == 'refs/heads/main' }}"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build container
        run: docker build -t cubicrootxyz/database-dumper-sidecar:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/database-dumper-sidecar:latest
      
